# Generated by Django 3.1.2 on 2021-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offered_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.CharField(max_length=10)),
                ('CS1000', models.IntegerField()),
                ('CS1010', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_data',
            name='course_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesters',
            name='semester_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
